import React, { Component } from 'react';
// import ReactDOM from 'react-dom';
import renderer from 'react-test-renderer';
import { shallow } from 'enzyme';
import ErrorBoundary from './ErrorBoundary';

class ComponentWithError extends Component { // eslint-disable-line react/prefer-stateless-function
  render() {
    return (
      <div>
        <input type="text" value={null} />
      </div>
    );
  }
}

describe('<ErrorBoundary> window', () => {
  it('should match the snapshot', () => {
    const tree = renderer.create(<ErrorBoundary>Test</ErrorBoundary>).toJSON();
    expect(tree).toMatchSnapshot();
  });

  it('displays error message on error generated by child', () => {
    const wrapper = shallow(
      <ErrorBoundary>
        <ComponentWithError />
      </ErrorBoundary>
    );
    const error = new Error('test');
    wrapper.find(ComponentWithError).simulateError(error);
    expect(wrapper.html()).toEqual('<div><h1>Something went wrong.</h1></div>');
  });
});
